BaseURL = "https://lawulu.github.io/"

LanguageCode = "zh-CN"
HasCJKLanguage = true
Title = "璐濒殉漂流记"
Theme = "pacman"
pygmentsStyle = "default"
pygmentsUseClasses = true
RSSUri = "feed.xml"

[Author]
  Name = "Lawulu"

[Params]
  BottomIntroduce = "3x:No time for Lusers"
  Description = ""
  Subtitle = "Live Each Century As If It Were Your Last"
  Weibo = "log4j"
  
  Twitter = "inza9hi"
  GitHub = "lawulu"
  
  Imglogo = "img/logo.svg"
  AuthorImg = "img/author.jpg"
  # 日期时间格式
  DateFormat = "2006年01月02日"
  MonthFormat = "2006年01月"
  FancyBox = true

  # 使用多说评论
  [Params.DuoShuo]
    ShortName = "inza9hi"

  # 使用 Disqus 评论
  #[Params.Disqus]
  #  ShortName = "inza9hi"

  # Google 统计
  #[Params.GoogleAnalytics]
   # ID = "UA-10147768-2"

  # 多语言字符串
  [Params.Strings]
    Search = "搜索"
    PageNotFound = "你访问的页面不存在"
    ShowSideBar = "显示侧边栏"
    HideSideBar = "隐藏侧边栏"
    Categories = "分类"
    Archive = "归档"
    Tags = "标签"
    TagCloud = "标签云"
    Rss = "RSS 订阅"
    TableOfContents = "文章目录"

[Menu]
  [[Menu.Main]]
    Name = "首页"
    URL = "/"
    Weight = 1
  [[Menu.Main]]
    Name = "关于"
    URL = "/about"
    Weight = 2


  [[Menu.Main]]
    Name = "关于"
    URL = "/about"
    Weight = 2
